(()=>{'use strict';const cats=[['ranked3','段位三人场'],['ranked4','段位四人场'],['friendly3','友人三人场'],['friendly4','友人四人场'],['event3','活动三人场'],['event4','活动四人场']],periodNames={total:'总',east:'东',south:'南'};let category='ranked3',period='total',data;
const $=id=>document.getElementById(id);function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}const pct=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'—';
function tabs(){for(const[id,name]of cats){const b=el('button',name);b.type='button';b.dataset.key=id;b.onclick=()=>{category=id;render();};$('categories').append(b);}for(const[id,name]of Object.entries(periodNames)){const b=el('button',name);b.type='button';b.dataset.key=id;b.onclick=()=>{period=id;render();};$('periods').append(b);}}
function render(){for(const b of $('categories').children)b.setAttribute('aria-pressed',String(b.dataset.key===category));for(const b of $('periods').children)b.setAttribute('aria-pressed',String(b.dataset.key===period));$('heading').textContent=cats.find(x=>x[0]===category)[1]+' · '+periodNames[period];high();$('metrics').replaceChildren();$('ranks').replaceChildren();const g=data.groups.find(x=>x.key===category),r=g?.periods?.[period];$('empty').hidden=!!r;$('placement').hidden=!r;
$('scope').textContent=period==='total'?'统计口径：东风＋半庄，按累计次数合并。':'统计口径：'+(period==='east'?'东风':'半庄')+'累计数据。';if(g?.otherModes?.length)$('scope').textContent+=' 此分类还含特殊规则，未纳入东／南合计。';
if(!r){$('empty').textContent=g?.available?'服务器未返回此模式的统计，暂不推断为零场。':'此分类尚无服务器统计返回。';return;}
const average=r.games?r.positions.reduce((s,v,i)=>s+v*(i+1),0)/r.games:null;
const wins=r.outcomesKnown?r.selfDraws+r.ron:null;const rate=v=>r.outcomesKnown?pct(v,r.rounds):'—';
for(const[name,value]of [['总场次',r.games],['总局数',r.rounds],['平均顺位',average===null?'—':average.toFixed(3)],['一位率',pct(r.positions[0],r.games)],['和牌率',rate(wins)],['放铳率',rate(r.dealIns)],['自摸率（和牌中）',wins?pct(r.selfDraws,wins):'—'],['平均打点',wins?(r.winPoints/wins).toFixed(0):'—'],['平均和牌巡目',wins?(r.winTurns/wins).toFixed(2):'—'],['副露率',pct(r.calls,r.rounds)],['立直率',pct(r.riichi,r.rounds)],['末位率',pct(r.positions.at(-1),r.games)],['被飞率',pct(r.fly,r.games)],['最高连庄',r.highestDealer],['流局率',rate(r.draws)],['被自摸率',rate(r.opponentSelfDraws)],['横移率',rate(r.sideways)],['和牌次数',wins??'—'],['放铳次数',r.outcomesKnown?r.dealIns:'—'],['立直局数',r.riichi]]){const c=el('div',undefined,'card');c.append(el('div',name,'muted'),el('div',String(value),'value'));$('metrics').append(c);}
r.positions.forEach((v,i)=>{const x=el('div',undefined,'rank'),bar=el('div',undefined,'bar'),fill=el('div',undefined,'fill');fill.style.width=(r.games?v/r.games*100:0)+'%';bar.append(fill);x.append(el('span',(i+1)+'位'),bar,el('span',`${v} · ${pct(v,r.games)}`));$('ranks').append(x);});}
const SUIT_ORDER={m:0,p:1,s:2,z:3};
function tileTokens(value){const text=String(value||'').toLowerCase();if(text==='bd')return['bd'];if(text==='back')return['back'];return text.match(/bd|back|[0-9][mpsz]/g)||[];}
function tileSort(a,b){const val=t=>t==='bd'?100:t==='back'?101:(SUIT_ORDER[t[1]]??9)*10+(t[0]==='0'?4.5:Number(t[0]));return val(a)-val(b);}
function meldTiles(value){const s=String(value||'').trim().toLowerCase();const match=s.match(/^([a-z_]+)\((.*)\)$/);let tiles=tileTokens(match?match[2]:s),closed=match?.[1]==='angang';
// Official legacy single-tile encoding denotes a concealed kong.
if(!match&&!s.includes('|')&&tiles.length===1&&tiles[0]!=='bd'&&tiles[0]!=='back'){const t=tiles[0],base=t[0]==='0'?'5'+t[1]:t;tiles=['back',base[0]==='5'&&base[1]!=='z'?'0'+base[1]:base,base,'back'];return tiles;}
if(closed&&tiles.length===4){const red=tiles.filter(t=>t[0]==='0'),normal=tiles.filter(t=>t[0]!=='0');return ['back',...(red.concat(normal).slice(0,2)),'back'];}
return tiles;}
function svgNode(tag,attrs={},text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==undefined)n.textContent=text;return n;}
function tileName(t){if(t==='bd')return'万能牌';if(t==='back')return'牌背';if(t[1]==='z')return['东','南','西','北','白','发','中'][Number(t[0])-1]||'未知牌';return(t[0]==='0'?'赤五':t[0])+({m:'万',p:'筒',s:'索'}[t[1]]||'');}
function tileFace(t){const node=el('span',undefined,'mj-tile');node.dataset.tile=t;node.setAttribute('role','img');node.setAttribute('aria-label',tileName(t));node.title=tileName(t);const svg=svgNode('svg',{viewBox:'0 0 44 62','aria-hidden':'true'});svg.append(svgNode('rect',{x:1,y:3,width:42,height:58,rx:5,fill:'#436b58'}),svgNode('rect',{x:1,y:1,width:42,height:56,rx:5,fill:'#faf7e9',stroke:'#d9d2b8','stroke-width':1}));
const ink=t[0]==='0'?'#be3532':'#215143';
if(t==='back'){svg.append(svgNode('rect',{x:5,y:5,width:34,height:47,rx:3,fill:'#286657',stroke:'#8bb299'}));for(let y=11;y<49;y+=8)svg.append(svgNode('path',{d:`M7 ${y} L22 ${y-5} L37 ${y}`,fill:'none',stroke:'#76a991','stroke-width':1}));}
else if(t==='bd'){svg.append(svgNode('path',{d:'M22 7 L26 18 L37 22 L26 26 L22 37 L18 26 L7 22 L18 18 Z',fill:'#c18b26'}),svgNode('text',{x:22,y:49,'text-anchor':'middle','font-size':12,'font-weight':700,fill:'#805a1d'},'万能'));}
else if(t[1]==='m'){svg.append(svgNode('text',{x:22,y:27,'text-anchor':'middle','font-size':25,'font-weight':800,fill:ink},t[0]==='0'?'五':['','一','二','三','四','五','六','七','八','九'][Number(t[0])]),svgNode('text',{x:22,y:49,'text-anchor':'middle','font-size':23,'font-weight':700,fill:'#b33630'},'萬'));}
else if(t[1]==='z'){if(t==='5z')svg.append(svgNode('rect',{x:11,y:12,width:22,height:33,rx:2,fill:'none',stroke:'#466ba1','stroke-width':3}));else svg.append(svgNode('text',{x:22,y:40,'text-anchor':'middle','font-size':31,'font-weight':750,fill:t==='7z'?'#b93631':t==='6z'?'#25754b':'#233746'},tileName(t)));}
else if(t[1]==='p'||t[1]==='s'){const n=t[0]==='0'?5:Number(t[0]);const layouts={1:[[22,29]],2:[[22,17],[22,42]],3:[[12,13],[22,29],[32,45]],4:[[12,16],[32,16],[12,43],[32,43]],5:[[12,13],[32,13],[22,29],[12,45],[32,45]],6:[[12,12],[32,12],[12,29],[32,29],[12,46],[32,46]],7:[[22,10],[12,24],[32,24],[12,36],[32,36],[12,48],[32,48]],8:[[12,10],[32,10],[12,23],[32,23],[12,36],[32,36],[12,49],[32,49]],9:[[11,12],[22,12],[33,12],[11,29],[22,29],[33,29],[11,46],[22,46],[33,46]]};for(const[x,y]of layouts[n]||[]){if(t[1]==='p'){const radius=n===1?11:n===9?4:5;svg.append(svgNode('circle',{cx:x,cy:y,r:radius,fill:'none',stroke:ink,'stroke-width':2}),svgNode('circle',{cx:x,cy:y,r:radius*0.43,fill:t[0]==='0'?'#be3532':'#4a7390'}));}else{svg.append(svgNode('rect',{x:x-2.5,y:y-(n===1?17:5),width:5,height:n===1?34:10,rx:2,fill:ink}),svgNode('path',{d:`M${x-4} ${y}h8`,stroke:'#96b392','stroke-width':1.3}));}}}
else svg.append(svgNode('text',{x:22,y:35,'text-anchor':'middle','font-size':11,fill:'#694a38'},'?'));
node.append(svg);return node;}
function tileGroup(tiles,label){const group=el('div',undefined,'mj-group');group.setAttribute('aria-label',label);for(const tile of tiles)group.append(tileFace(tile));return group;}
function high(){const root=$('highlights');root.replaceChildren();const h=data.highlights.find(h=>h.key===category);if(!h){root.append(el('p','此分类尚未返回个人主页展示的和牌。','muted'));return;}
const card=el('div',undefined,'highlight-hand');const top=el('div',undefined,'hand-title');top.append(el('h3',`${h.title||'和牌'} · ${h.fan} 番`));card.append(top);
// HighestHuRecord contains no yaku list. Do not infer situational yaku from tiles.
card.append(el('p','役种未提供','hand-yaku muted'));
const rail=el('div',undefined,'hand-scroll');rail.tabIndex=0;rail.setAttribute('aria-label','和牌牌型：暗牌、副露、和牌');const row=el('div',undefined,'hand-row');const concealed=h.hand.flatMap(tileTokens).sort(tileSort);if(concealed.length)row.append(tileGroup(concealed,'暗牌'));
if(h.melds.length){const melds=el('div',undefined,'mj-melds');melds.setAttribute('aria-label','副露');h.melds.forEach((m,i)=>melds.append(tileGroup(meldTiles(m),`副露 ${i+1}`)));row.append(melds);}
const winning=tileTokens(h.winningTile);if(winning.length)row.append(tileGroup(winning,'和牌'));rail.append(row);card.append(rail);root.append(card);}
(async()=>{try{const r=await fetch('../data/majsoul.json',{cache:'no-store'});if(!r.ok)throw Error('数据读取失败');data=await r.json();if(data.schema!==3)throw Error('请运行新版 OPEN_MAJSOUL.cmd，再运行 RUN_SYNC.cmd 更新累计统计。');data.groups??=[];data.highlights??=[];const dt=data.updatedAt?new Date(data.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未采集';$('profile').textContent=`${data.nickname} · ID ${data.friendId} · 三麻 ${data.levels?.three||'待采集'} / 四麻 ${data.levels?.four||'待采集'}`;$('status').textContent=`${data.status} · 更新时间（北京时间）：${dt}`;tabs();render();high();}catch(e){$('profile').textContent='累计统计尚未就绪';$('status').textContent=e.message;$('placement').hidden=true;}})();
})();
