(()=>{'use strict';const cats=[['ranked3','段位三人场'],['ranked4','段位四人场'],['friendly3','友人三人场'],['friendly4','友人四人场'],['event3','活动三人场'],['event4','活动四人场']],periodNames={total:'总',east:'东',south:'南'};let category='ranked3',period='total',data;
const $=id=>document.getElementById(id);function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}const pct=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'—';
function tabs(){for(const[id,name]of cats){const b=el('button',name);b.type='button';b.dataset.key=id;b.onclick=()=>{category=id;render();};$('categories').append(b);}for(const[id,name]of Object.entries(periodNames)){const b=el('button',name);b.type='button';b.dataset.key=id;b.onclick=()=>{period=id;render();};$('periods').append(b);}}
function render(){for(const b of $('categories').children)b.setAttribute('aria-pressed',String(b.dataset.key===category));for(const b of $('periods').children)b.setAttribute('aria-pressed',String(b.dataset.key===period));$('heading').textContent=cats.find(x=>x[0]===category)[1]+' · '+periodNames[period];high();$('metrics').replaceChildren();$('ranks').replaceChildren();const g=data.groups.find(x=>x.key===category),r=g?.periods?.[period];$('empty').hidden=!!r;$('placement').hidden=!r;
$('scope').textContent=period==='total'?'统计口径：东风＋半庄，按累计次数合并。':'统计口径：'+(period==='east'?'东风':'半庄')+'累计数据。';if(g?.otherModes?.length)$('scope').textContent+=' 此分类还含特殊规则，未纳入东／南合计。';
if(!r){$('empty').textContent=g?.available?'服务器未返回此模式的统计，暂不推断为零场。':'此分类尚无服务器统计返回。';return;}
const average=r.games?r.positions.reduce((s,v,i)=>s+v*(i+1),0)/r.games:null;
const wins=r.outcomesKnown?r.selfDraws+r.ron:null;const rate=v=>r.outcomesKnown?pct(v,r.rounds):'—';
for(const[name,value]of [['总场次',r.games],['总局数',r.rounds],['平均顺位',average===null?'—':average.toFixed(3)],['一位率',pct(r.positions[0],r.games)],['和牌率',rate(wins)],['放铳率',rate(r.dealIns)],['自摸率（和牌中）',wins?pct(r.selfDraws,wins):'—'],['平均打点',wins?(r.winPoints/wins).toFixed(0):'—'],['平均和牌巡目',wins?(r.winTurns/wins).toFixed(2):'—'],['副露率',pct(r.calls,r.rounds)],['立直率',pct(r.riichi,r.rounds)],['末位率',pct(r.positions.at(-1),r.games)],['被飞率',pct(r.fly,r.games)],['最高连庄',r.highestDealer],['流局率',rate(r.draws)],['被自摸率',rate(r.opponentSelfDraws)],['横移率',rate(r.sideways)],['和牌次数',wins??'—'],['放铳次数',r.outcomesKnown?r.dealIns:'—'],['立直局数',r.riichi]]){const c=el('div',undefined,'card');c.append(el('div',name,'muted'),el('div',String(value),'value'));$('metrics').append(c);}
r.positions.forEach((v,i)=>{const x=el('div',undefined,'rank'),bar=el('div',undefined,'bar'),fill=el('div',undefined,'fill');fill.style.width=(r.games?v/r.games*100:0)+'%';bar.append(fill);x.append(el('span',(i+1)+'位'),bar,el('span',`${v} · ${pct(v,r.games)}`));$('ranks').append(x);});}
function tile(t){return String(t).replace(/0([mps])/g,'赤5$1').replace(/([0-9])m/g,'$1万 ').replace(/([0-9])p/g,'$1筒 ').replace(/([0-9])s/g,'$1索 ').replace(/([1-7])z/g,(_,n)=>['东','南','西','北','白','发','中'][Number(n)-1]+' ');}
function high(){const root=$('highlights');root.replaceChildren();const records=data.highlights.filter(h=>h.key===category);if(!records.length){root.append(el('p','此分类尚未返回个人主页展示的和牌。','muted'));return;}
records.forEach(h=>{const card=el('div',undefined,'card');card.append(el('p','游戏内个人主页展示','muted'),el('h3',h.title||'和牌记录'),el('p',`${h.fan} 番 · 宝牌 ${h.dora}`));const hand=el('div',undefined,'tileline');h.hand.forEach(t=>hand.append(el('span',tile(t),'tile')));card.append(hand);if(h.melds.length)card.append(el('p','副露：'+h.melds.map(tile).join(' / ')));if(h.winningTile)card.append(el('p','和牌：'+tile(h.winningTile)));root.append(card);});}
(async()=>{try{const r=await fetch('../data/majsoul.json',{cache:'no-store'});if(!r.ok)throw Error('数据读取失败');data=await r.json();if(data.schema!==3)throw Error('请运行新版 OPEN_MAJSOUL.cmd，再运行 RUN_SYNC.cmd 更新累计统计。');data.groups??=[];data.highlights??=[];const dt=data.updatedAt?new Date(data.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未采集';$('profile').textContent=`${data.nickname} · ID ${data.friendId} · 三麻 ${data.levels?.three||'待采集'} / 四麻 ${data.levels?.four||'待采集'}`;$('status').textContent=`${data.status} · 更新时间（北京时间）：${dt}`;tabs();render();high();}catch(e){$('profile').textContent='累计统计尚未就绪';$('status').textContent=e.message;$('placement').hidden=true;}})();
})();
